### ISSUE TITLE
Add postinstall script to copy a config file

### ISSUE THREAD

**Issue by jimlambie** [dadi/api-mongodb#3]
Using this adapter with DADI API requires having a config file in the api installation. This package should have a postinstall script to handle that.

**Comment by jimlambie** [comment]
For reference:
* https://github.com/dadi/api-filestore/blob/master/package.json#L9
* https://github.com/dadi/api-filestore/blob/master/scripts/copy-config.js

**Comment by eduardoboucas** [comment]
Can we close this, now that CLI is in the mix?
